t = 
{
    "id":4353143668906,
    "admin_graphql_api_id":"gid://shopify/Order/4353143668906",
    "app_id":580111,
    "browser_ip":"91.136.194.122",
    "buyer_accepts_marketing":false,
    "cancel_reason":"None",
    "cancelled_at":"None",
    "cart_token":"a6d73443e510ed20be4d4ac3e64d775b",
    "checkout_id":23191566581930,
    "checkout_token":"ffe6b020895a215487df4052c3d353b5",
    "client_details":{
       "accept_language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
       "browser_height":881,
       "browser_ip":"91.136.194.122",
       "browser_width":1920,
       "session_hash":"None",
       "user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
    },
    "closed_at":"2022-03-19T03:14:42+01:00",
    "confirmed":true,
    "contact_email":"sebastian.daum@t-online.de",
    "created_at":"2022-03-19T03:10:04+01:00",
    "currency":"EUR",
    "current_subtotal_price":"0.00",
    "current_subtotal_price_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "current_total_discounts":"64.90",
    "current_total_discounts_set":{
       "shop_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       }
    },
    "current_total_duties_set":"None",
    "current_total_price":"0.00",
    "current_total_price_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "current_total_tax":"0.00",
    "current_total_tax_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "customer_locale":"de-DE",
    "device_id":"None",
    "discount_codes":[
       {
          "code":"Base100",
          "amount":"64.90",
          "type":"percentage"
       }
    ],
    "email":"sebastian.daum@t-online.de",
    "estimated_taxes":false,
    "financial_status":"paid",
    "fulfillment_status":"fulfilled",
    "gateway":"None",
    "landing_site":"/?_ab=0&_fd=0&_sc=1",
    "landing_site_ref":"None",
    "location_id":"None",
    "name":"#BS1056",
    "note":"None",
    "note_attributes":[
       
    ],
    "number":56,
    "order_number":1056,
    "order_status_url":"https://www.baseshirt.de/49877778602/orders/607aba9fcd3b9c5141ed3acaa2122d03/authenticate?key=fbdea5i2c6d3199a8c1add91b734bfb",
    "original_total_duties_set":"None",
    "payment_gateway_names":[
       
    ],
    "phone":"None",
    "presentment_currency":"EUR",
    "processed_at":"2022-03-19T03:10:03+01:00",
    "processing_method":"free",
    "reference":"None",
    "referring_site":"",
    "source_identifier":"None",
    "source_name":"web",
    "source_url":"None",
    "subtotal_price":"0.00",
    "subtotal_price_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "tags":"",
    "tax_lines":[
       
    ],
    "taxes_included":true,
    "test":false,
    "token":"607aba9fcd3b9c5141ed3acaa2122d03",
    "total_discounts":"64.90",
    "total_discounts_set":{
       "shop_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       }
    },
    "total_line_items_price":"64.90",
    "total_line_items_price_set":{
       "shop_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"64.90",
          "currency_code":"EUR"
       }
    },
    "total_outstanding":"0.00",
    "total_price":"0.00",
    "total_price_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "total_price_usd":"0.00",
    "total_shipping_price_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "total_tax":"0.00",
    "total_tax_set":{
       "shop_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       },
       "presentment_money":{
          "amount":"0.00",
          "currency_code":"EUR"
       }
    },
    "total_tip_received":"0.00",
    "total_weight":0,
    "updated_at":"2022-03-19T03:14:42+01:00",
    "user_id":"None",
    "billing_address":{
       "first_name":"Sebastian",
       "address1":"Auf der Gunst 7",
       "phone":"0177 4003071",
       "city":"Schwerte",
       "zip":"58239",
       "province":"None",
       "country":"Germany",
       "last_name":"Daum",
       "address2":"None",
       "company":"",
       "latitude":51.4463885,
       "longitude":7.5504863,
       "name":"Sebastian Daum",
       "country_code":"DE",
       "province_code":"None"
    },
    "customer":{
       "id":4486397100202,
       "email":"sebastian.daum@t-online.de",
       "accepts_marketing":false,
       "created_at":"2020-12-11T05:23:22+01:00",
       "updated_at":"2022-03-19T03:10:04+01:00",
       "first_name":"Sebastian",
       "last_name":"Daum",
       "orders_count":5,
       "state":"disabled",
       "total_spent":"329.35",
       "last_order_id":4353143668906,
       "note":"None",
       "verified_email":true,
       "multipass_identifier":"None",
       "tax_exempt":false,
       "phone":"None",
       "tags":"",
       "last_order_name":"#BS1056",
       "currency":"EUR",
       "accepts_marketing_updated_at":"2020-12-11T05:23:22+01:00",
       "marketing_opt_in_level":"None",
       "sms_marketing_consent":"None",
       "admin_graphql_api_id":"gid://shopify/Customer/4486397100202",
       "default_address":{
          "id":7328772653226,
          "customer_id":4486397100202,
          "first_name":"Sebastian",
          "last_name":"Daum",
          "company":"",
          "address1":"Auf der Gunst 7",
          "address2":"None",
          "city":"Schwerte",
          "province":"None",
          "country":"Germany",
          "zip":"58239",
          "phone":"0177 4003071",
          "name":"Sebastian Daum",
          "province_code":"None",
          "country_code":"DE",
          "country_name":"Germany",
          "default":true
       }
    },
    "discount_applications":[
       {
          "target_type":"line_item",
          "type":"discount_code",
          "value":"100.0",
          "value_type":"percentage",
          "allocation_method":"across",
          "target_selection":"all",
          "code":"Base100"
       }
    ],
    "fulfillments":[
       {
          "id":3874352824490,
          "admin_graphql_api_id":"gid://shopify/Fulfillment/3874352824490",
          "created_at":"2022-03-19T03:14:42+01:00",
          "location_id":56544755882,
          "name":"#BS1056.1",
          "order_id":4353143668906,
          "origin_address":{
             
          },
          "receipt":{
             
          },
          "service":"manual",
          "shipment_status":"None",
          "status":"success",
          "tracking_company":"None",
          "tracking_number":"None",
          "tracking_numbers":[
             
          ],
          "tracking_url":"None",
          "tracking_urls":[
             
          ],
          "updated_at":"2022-03-19T03:14:42+01:00",
          "line_items":[
             {
                "id":10985910796458,
                "admin_graphql_api_id":"gid://shopify/LineItem/10985910796458",
                "fulfillable_quantity":0,
                "fulfillment_service":"manual",
                "fulfillment_status":"fulfilled",
                "gift_card":false,
                "grams":0,
                "name":"Nano Softshelljacke Herren - schwarz / M",
                "origin_location":{
                   "id":2603404787882,
                   "country_code":"DE",
                   "province_code":"",
                   "name":"BASESHIRT",
                   "address1":".",
                   "address2":".",
                   "city":".",
                   "zip":"58239"
                },
                "price":"49.95",
                "price_set":{
                   "shop_money":{
                      "amount":"49.95",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"49.95",
                      "currency_code":"EUR"
                   }
                },
                "product_exists":true,
                "product_id":5916854452394,
                "properties":[
                   
                ],
                "quantity":1,
                "requires_shipping":true,
                "sku":"5310114",
                "taxable":true,
                "title":"Nano Softshelljacke Herren",
                "total_discount":"0.00",
                "total_discount_set":{
                   "shop_money":{
                      "amount":"0.00",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"0.00",
                      "currency_code":"EUR"
                   }
                },
                "variant_id":37005896122538,
                "variant_inventory_management":"None",
                "variant_title":"schwarz / M",
                "vendor":"Malfini",
                "tax_lines":[
                   
                ],
                "duties":[
                   
                ],
                "discount_allocations":[
                   {
                      "amount":"49.95",
                      "amount_set":{
                         "shop_money":{
                            "amount":"49.95",
                            "currency_code":"EUR"
                         },
                         "presentment_money":{
                            "amount":"49.95",
                            "currency_code":"EUR"
                         }
                      },
                      "discount_application_index":0
                   }
                ]
             },
             {
                "id":10985910829226,
                "admin_graphql_api_id":"gid://shopify/LineItem/10985910829226",
                "fulfillable_quantity":0,
                "fulfillment_service":"manual",
                "fulfillment_status":"fulfilled",
                "gift_card":false,
                "grams":0,
                "name":"Brave T-Shirt Damen - hell anthrazit / XS",
                "origin_location":{
                   "id":2603404787882,
                   "country_code":"DE",
                   "province_code":"",
                   "name":"BASESHIRT",
                   "address1":".",
                   "address2":".",
                   "city":".",
                   "zip":"58239"
                },
                "price":"14.95",
                "price_set":{
                   "shop_money":{
                      "amount":"14.95",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"14.95",
                      "currency_code":"EUR"
                   }
                },
                "product_exists":true,
                "product_id":5916871852202,
                "properties":[
                   
                ],
                "quantity":1,
                "requires_shipping":true,
                "sku":"1568312",
                "taxable":true,
                "title":"Brave T-Shirt Damen",
                "total_discount":"0.00",
                "total_discount_set":{
                   "shop_money":{
                      "amount":"0.00",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"0.00",
                      "currency_code":"EUR"
                   }
                },
                "variant_id":37006228455594,
                "variant_inventory_management":"None",
                "variant_title":"hell anthrazit / XS",
                "vendor":"Malfini-Premium",
                "tax_lines":[
                   
                ],
                "duties":[
                   
                ],
                "discount_allocations":[
                   {
                      "amount":"14.95",
                      "amount_set":{
                         "shop_money":{
                            "amount":"14.95",
                            "currency_code":"EUR"
                         },
                         "presentment_money":{
                            "amount":"14.95",
                            "currency_code":"EUR"
                         }
                      },
                      "discount_application_index":0
                   }
                ]
             }
          ]
       }
    ],
    "line_items":[
       {
          "id":10985910796458,
          "admin_graphql_api_id":"gid://shopify/LineItem/10985910796458",
          "fulfillable_quantity":0,
          "fulfillment_service":"manual",
          "fulfillment_status":"fulfilled",
          "gift_card":false,
          "grams":0,
          "name":"Nano Softshelljacke Herren - schwarz / M",
          "origin_location":{
             "id":2603404787882,
             "country_code":"DE",
             "province_code":"",
             "name":"BASESHIRT",
             "address1":".",
             "address2":".",
             "city":".",
             "zip":"58239"
          },
          "price":"49.95",
          "price_set":{
             "shop_money":{
                "amount":"49.95",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"49.95",
                "currency_code":"EUR"
             }
          },
          "product_exists":true,
          "product_id":5916854452394,
          "properties":[
             
          ],
          "quantity":1,
          "requires_shipping":true,
          "sku":"5310114",
          "taxable":true,
          "title":"Nano Softshelljacke Herren",
          "total_discount":"0.00",
          "total_discount_set":{
             "shop_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             }
          },
          "variant_id":37005896122538,
          "variant_inventory_management":"None",
          "variant_title":"schwarz / M",
          "vendor":"Malfini",
          "tax_lines":[
             
          ],
          "duties":[
             
          ],
          "discount_allocations":[
             {
                "amount":"49.95",
                "amount_set":{
                   "shop_money":{
                      "amount":"49.95",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"49.95",
                      "currency_code":"EUR"
                   }
                },
                "discount_application_index":0
             }
          ]
       },
       {
          "id":10985910829226,
          "admin_gra2022-03-19T10:13:14.173877+00:00 app[web.1]: phql_api_id":"gid://shopify/LineItem/10985910829226",
          "fulfillable_quantity":0,
          "fulfillment_service":"manual",
          "fulfillment_status":"fulfilled",
          "gift_card":false,
          "grams":0,
          "name":"Brave T-Shirt Damen - hell anthrazit / XS",
          "origin_location":{
             "id":2603404787882,
             "country_code":"DE",
             "province_code":"",
             "name":"BASESHIRT",
             "address1":".",
             "address2":".",
             "city":".",
             "zip":"58239"
          },
          "price":"14.95",
          "price_set":{
             "shop_money":{
                "amount":"14.95",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"14.95",
                "currency_code":"EUR"
             }
          },
          "product_exists":true,
          "product_id":5916871852202,
          "properties":[
             
          ],
          "quantity":1,
          "requires_shipping":true,
          "sku":"1568312",
          "taxable":true,
          "title":"Brave T-Shirt Damen",
          "total_discount":"0.00",
          "total_discount_set":{
             "shop_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             }
          },
          "variant_id":37006228455594,
          "variant_inventory_management":"None",
          "variant_title":"hell anthrazit / XS",
          "vendor":"Malfini-Premium",
          "tax_lines":[
             
          ],
          "duties":[
             
          ],
          "discount_allocations":[
             {
                "amount":"14.95",
                "amount_set":{
                   "shop_money":{
                      "amount":"14.95",
                      "currency_code":"EUR"
                   },
                   "presentment_money":{
                      "amount":"14.95",
                      "currency_code":"EUR"
                   }
                },
                "discount_application_index":0
             }
          ]
       }
    ],
    "payment_terms":"None",
    "refunds":[
       
    ],
    "shipping_address":{
       "first_name":"Sebastian",
       "address1":"Auf der Gunst 7",
       "phone":"0177 4003071",
       "city":"Schwerte",
       "zip":"58239",
       "province":"None",
       "country":"Germany",
       "last_name":"Daum",
       "address2":"None",
       "company":"",
       "latitude":51.4463885,
       "longitude":7.5504863,
       "name":"Sebastian Daum",
       "country_code":"DE",
       "province_code":"None"
    },
    "shipping_lines":[
       {
          "id":3597213728938,
          "carrier_identifier":"None",
          "code":"Standard",
          "delivery_category":"None",
          "discounted_price":"0.00",
          "discounted_price_set":{
             "shop_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             }
          },
          "phone":"None",
          "price":"0.00",
          "price_set":{
             "shop_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             },
             "presentment_money":{
                "amount":"0.00",
                "currency_code":"EUR"
             }
          },
          "requested_fulfillment_service_id":"None",
          "source":"shopify",
          "title":"Standard",
          "tax_lines":[
             
          ],
          "discount_allocations":[
             
          ]
       }
    ]
 }